version: '2.0'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    environment:
        - DB_HOST='db'
    depends_on:
      - db

volumes:
  postgres_data:
