# Generated by Django 4.2 on 2023-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0002_alter_customuser_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.FileField(upload_to='tmp_upload'),
        ),
    ]
