# Generated by Django 4.2 on 2023-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0003_alter_customuser_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='voteanswer',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='voteanswer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='votequestion',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='votequestion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='hasker_app.tag'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer_id',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
