# Generated by Django 4.2 on 2023-05-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0003_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
