# Generated by Django 4.2 on 2023-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0004_rename_question_id_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votes_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture_data',
            field=models.BinaryField(blank=True),
        ),
    ]
